# -*- coding: utf-8 -*-
"""words-mail

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1VhC7oenTqxJoh-DHEkgBHg3mQs-Ji200
"""

import re
def modify_string(input_string):
    cleaned_string = re.sub(r'[^\w\s]', '', input_string)
    modified_string = cleaned_string.lower()
    modified_string = modified_string.replace(" ", "").replace("\n", "")
    return modified_string

def add_list_to_text(existing_text, elements_list):
    elements_str = ", ".join(elements_list)
    modified_text = f"{existing_text} {elements_str}"
    return modified_text

if __name__ == "__main__":

    job_desc = """Experienced software engineer skilled in Python, Java, and Haskell. Also proficient in web development."""

    jd = modify_string(job_desc)
    cv = """Software engineer with experience in Python and Java."""

    c = modify_string(cv)

    lst=["softwaredeveloper","webdeveloper","mobileappdeveloper","front-enddeveloper","frontenddeveloper","back-enddeveloper","full-stackdeveloper","fullstackdeveloper","fullstackengineer","databasedeveloper","devopsengineer","softwareengineer","qaengineer","testautomationengineer","cloudengineer",
        "dataengineer","machinelearningengineer","aiengineer","gamedeveloper","embeddedsystemsengineer","securityengineer","uidesigner","uxdesigner","agiledeveloper",
    "productmanager","projectmanager","technicalprojectmanager","scrummaster","productowner","businessanalyst","requirementsanalyst","productmarketingmanager",
    "datascientist","dataanalyst","businessintelligenceanalyst","dataengineer","dataarchitect","bigdataengineer","machinelearningengineer","aispecialist",
    "networkengineer","systemadministrator","cloudarchitect","securityanalyst","itsupportspecialist","itconsultant","itmanager",
    "graphicdesigner","ux/uidesigner","motiondesigner","gamedesigner","3dartist","videoeditor","illustrator", "hardwareengineer", "embeddedsystemsengineer","firmwareengineer","vlsiengineer",
    "ethicalhacker","cybersecurityanalyst","securityconsultant","html","css","javascript","informationsecurityofficer","penetrationtester","securityoperationscenteranalyst",
    "machinelearningengineer","deeplearningengineer","deeplearning","airesearcher","computervisionengineer","naturallanguageprocessing","reinforcementlearningengineer",
    "testautomationengineer","performancetestingengineer","manualtester","sdet",
    "businessanalyst","dataanalyst","businessintelligenceanalyst","systemsanalyst","quantitativeanalyst",
    "databaseadministrator","databasedeveloper","datawarehouseengineer","bigdataengineer","hadoopdeveloper",
    "devops","buildandreleaseengineer","continuousintegration","continuousdelivery",
    "iotengineer","roboticsengineer","automationengineer","controlsystemsengineer","css",
    "cloudengineer","cloudarchitect","awssolutionsarchitect","aws","azuresolutionsarchitect","googlecloudarchitect",
    "python","java","javascript","c++","c#","php","swift","kotlin","typescript","ruby","go","rust","scala","haskell","sql","html","css",
    "react","angular","vue.js","node.js","django","flask","spring",".net","asp.net","tensorflow","pytorch","keras","opencv","spark","hadoop",
    "docker","kubernetes","jenkins","git","mysql","postgresql","mongodb","firebase","elasticsearch","graphql","restfulapi","oauth","oauth2",
    "json","xml","oauth","oauth2","soap","ci/cd","cd","microservices","serverless","blockchain","ar/vr","rpa","agile","scrum","waterfall","kanban","sdlc",
    "tdd", "testdrivendevelopment","bdd","behaviordrivendevelopment","uml","unifiedmodelinglanguage","ooad","object-orientedanalysisanddesign","solidprinciples",
    "designpatterns","restfulapi","graphql","react" ,"native","redux","express.js","flask",
    "djangorestframework","asp.netcore","springboot","bootstrap","material-ui","sass","less","websockets","progressivewebapps","single-pageapplication",
    "server-siderendering","client-siderendering","cross-originresourcesharing","swiftui","androidjetpack","xamarin",
    "phonegap","cordova","flutter","firebasecloudmessaging","pushnotifications","in-apppurchases","mobileanalytics",
    "amazonwebservices","aws","microsoftazure","googlecloudplatform","serverlessarchitecture","awslambda","azurefunctions","googlecloudfunctions",
    "infrastructureascode","iac","terraform","cloudformation","ansible","puppet","chef","sitereliabilityengineering","cloudsecurity",
    "apachehadoop","apachespark","apachekafka","elasticsearch","kibana","logstash","java","html5","css3"
    "datawarehousing","etl","datavisualization","tableau","powerbi","datamining","sentimentanalysis","timeseriesanalysis",
    "microsoftsqlserver","oracledatabase","mariadb","sqlite","nosqldatabases","databasereplication","databasesharding","datamigration",
    "databaseindexing","aicd","machinelearning","artificialintelligence","naturallanguageunderstanding","transferlearning",
    "imagerecognition","speechrecognition","gans","autoencoders","recommendersystems","timeseriesforecasting","security","penetrationtesting",
    "vulnerabilityassessment","siem","waf","ddosmitigation","incidentresponse","threathunting","cryptography","pki","publickeyinfrastructure","securecodingpractices","mqtt",
    "coap ","zigbee","lorawan","bluetoothlowenergy","industrialiot","homeautomation","smartcities","edgecomputing","armcortex-m",
    "avrmicrocontrollers","raspberrypi","arduino","fpga","real-rimeoperatingsystems","unrealengine","unityengine","cocos2d-x","mephysics",
    "gamenetworking","gameai","gamedesignpatterns","webdevelopment","jsmongodb", "express","tailwindcss",
    "tcp","ip","udp","http","https","dns","nat","vpn","loadbalancing","sd-wan","networksecurity","pandas","numpy","scipy","scikit-learn",
    "rprogramming","r","statisticalanalysis","hypothesistesting","a/btesting","timeseriesanalysis"]
    a=[]
    b=[]
    res=[]
    for i in lst:
      if i in jd:
        a.append(i)
      if i in c:
        b.append(i)
    common=[]
    for i in a:
      if i in b:
        common.append(i)
    score=len(common)/len(a)
    print("Score: ",score)
    print("Recommended Changes:")
    for i in lst:
      if i in jd and i not in c:
        res.append(i)
    missing_words=set(res)
    for element in missing_words:
        print(element)
    print('\n')
    if score==1:
      print("Prepare for your interviews")
    else:
        print("Do you want to continue with the original version?(Y/N)")
        reply=input()
        if reply=='N':
            print('\n')
            print("Updated CV:")
            cv=cv+'\n'
            cv+='Skills:'+'\n'
            output = ', '.join(str(item) for item in missing_words)
            cv+=output
            print(cv)
        else:
          print("You chose Original Version")

import re

def extract_name_and_email(cv_text):
    email_pattern = r'\b[A-Za-z0-9._%+-]+@[A-Za-z0-9.-]+\.[A-Z|a-z]{2,}\b'
    emails = re.findall(email_pattern, cv_text)
    return emails

if __name__ == "__main__":
    cv = """
    Alfred Pennyworth
Product Manager
Silicon Valley, CA, USA
I
(123) 456-7890
#
	wie-staff@ieee.org
ð
apennyworth
§
apennyworth
Professional Summary
Seasoned Product Manager with over 20 years of experience in software development and product
management, having worked at all FAANG companies. Exceptional leadership skills, strategic
thinking, and a track record of managing products from conception to market success.
Skills
Product management, Agile methodologies, Leadership, Communication, Project
management, User Experience Design, Market Research, Data Analysis, Java,
Python, JavaScript, HTML/CSS, SQL, AWS
Experience
2017 –
Present
Product Manager, Google, Mountain View, CA, USA
Leading cross-functional teams to design, develop, and launch innovative products. Devel￾oping product strategies and making data-driven decisions to improve user experience and
meet business goals.
2012 – 2017 Software Development Engineer III, Amazon, Seattle, WA, USA
Led a team of developers in building scalable and high-performing e-commerce applications.
Successfully delivered multiple projects within the stipulated time and budget.
2007 – 2012 Software Development Engineer II, Apple, Cupertino, CA, USA
Designed and implemented software components for various Apple services. Optimized the
performance of applications and improved code quality through thorough testing.
2002 – 2007 Software Development Engineer I, Netflix, Los Gatos, CA, USA
Developed and maintained the user interface for the Netflix web application. Worked closely
with product managers and designers to create an optimal user experience.
1999 – 2002 Software Development Engineer I, Facebook, Menlo Park, CA, USA
Played a key role in the development of early Facebook features. Implemented scalable
back-end services using Java and SQL.
Education
2016 – 2018 Master of Business Administration, Stanford University, Stanford, CA, USA
1997 – 1999 Master of Science in Computer Science, Massachusetts Institute of Technology,
Cambridge, MA, USA
1994 – 1997 Bachelor of Science in Computer Science, University of California, Berkeley,
Berkeley, CA, USA
Projects
1/2
2020 – Personal Project: Home Automation System
Present Developed a smart home automation system using Raspberry Pi and Python. The system
automates various home appliances based on user behavior and preferences, contributing to
energy saving and improved user convenience.
2/2
    """

    emails = extract_name_and_email(cv)
    print("Email(s):", emails)